### ISSUE TITLE
Not able to upload header img in prod

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#159]
java.io.FileNotFoundException: class path resource [static/img/logo.png] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app/target/questions-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/static/img/logo.png

stack:
`at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218)
2016-10-10T18:08:12.073854+00:00 app[web.1]:    at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:181)
2016-10-10T18:08:12.073868+00:00 app[web.1]:    at com.nearsoft.questions.service.impl.StorageServiceImpl.replaceFile(StorageServiceImpl.java:20)
2016-10-10T18:08:12.073943+00:00 app[web.1]:    at com.nearsoft.questions.controller.AdminController.handleFileUpload(AdminController.java:47)
2016-10-10T18:08:12.073947+00:00 app[web.1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-10-10T18:08:12.073977+00:00 app[web.1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-10-10T18:08:12.074005+00:00 app[web.1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-10-10T18:08:12.074034+00:00 app[web.1]:    at java.lang.reflect.Method.invoke(Method.java:498)
2016-10-10T18:08:12.074068+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
2016-10-10T18:08:12.074102+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
2016-10-10T18:08:12.074134+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
2016-10-10T18:08:12.074171+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
2016-10-10T18:08:12.074209+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
2016-10-10T18:08:12.074249+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
2016-10-10T18:08:12.074287+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
2016-10-10T18:08:12.074327+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
2016-10-10T18:08:12.074365+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
2016-10-10T18:08:12.074402+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
2016-10-10T18:08:12.074439+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
2016-10-10T18:08:12.074489+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
2016-10-10T18:08:12.074498+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
2016-10-10T18:08:12.074526+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
2016-10-10T18:08:12.074555+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.074588+00:00 app[web.1]:    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2016-10-10T18:08:12.074616+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.074644+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.074674+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
2016-10-10T18:08:12.074703+00:00 app[web.1]:    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
2016-10-10T18:08:12.074732+00:00 app[web.1]:    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
2016-10-10T18:08:12.074761+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.074789+00:00 app[web.1]:    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-10-10T18:08:12.074818+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.074889+00:00 app[web.1]:    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
2016-10-10T18:08:12.075005+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075037+00:00 app[web.1]:    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
2016-10-10T18:08:12.075094+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075133+00:00 app[web.1]:    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
2016-10-10T18:08:12.075172+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075210+00:00 app[web.1]:    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
2016-10-10T18:08:12.075257+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075273+00:00 app[web.1]:    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
2016-10-10T18:08:12.075329+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075379+00:00 app[web.1]:    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
2016-10-10T18:08:12.075418+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075445+00:00 app[web.1]:    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
2016-10-10T18:08:12.075479+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075511+00:00 app[web.1]:    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
2016-10-10T18:08:12.075541+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.075569+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075600+00:00 app[web.1]:    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
2016-10-10T18:08:12.075631+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075668+00:00 app[web.1]:    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
2016-10-10T18:08:12.075700+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.075730+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
2016-10-10T18:08:12.075762+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
2016-10-10T18:08:12.075832+00:00 app[web.1]:    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
2016-10-10T18:08:12.075879+00:00 app[web.1]:    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
2016-10-10T18:08:12.075927+00:00 app[web.1]:    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
2016-10-10T18:08:12.075950+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.075977+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.076006+00:00 app[web.1]:    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
2016-10-10T18:08:12.076034+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.076094+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.076135+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.076166+00:00 app[web.1]:    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
2016-10-10T18:08:12.076193+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.076226+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.076252+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.076281+00:00 app[web.1]:    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
2016-10-10T18:08:12.076308+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.076336+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.076363+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.076390+00:00 app[web.1]:    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
2016-10-10T18:08:12.076417+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-10-10T18:08:12.076447+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-10-10T18:08:12.076489+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-10-10T18:08:12.076518+00:00 app[web.1]:    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
2016-10-10T18:08:12.076545+00:00 app[web.1]:    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
2016-10-10T18:08:12.076573+00:00 app[web.1]:    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
2016-10-10T18:08:12.076601+00:00 app[web.1]:    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2016-10-10T18:08:12.076629+00:00 app[web.1]:    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
2016-10-10T18:08:12.076656+00:00 app[web.1]:    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2016-10-10T18:08:12.076684+00:00 app[web.1]:    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
2016-10-10T18:08:12.076711+00:00 app[web.1]:    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
2016-10-10T18:08:12.076738+00:00 app[web.1]:    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
2016-10-10T18:08:12.076765+00:00 app[web.1]:    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
2016-10-10T18:08:12.076821+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
2016-10-10T18:08:12.076849+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
2016-10-10T18:08:12.076875+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-10-10T18:08:12.076901+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-10-10T18:08:12.076927+00:00 app[web.1]:    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2016-10-10T18:08:12.076955+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)`

**Comment by wdonet** [comment]
We followed a different approach , instead of uploading the image, we change the image URL by configuration.
Closing
